export const CATEGORIES = [
  {
    id: "nakshi-katha",
    nameEn: "Nakshi Katha",
    nameBn: "নকশী কাঁথা",
    image: "https://i.pinimg.com/736x/cb/1e/11/cb1e117f76b2d98514bc81a54c9ab60d.jpg",
    descEn: "Traditional hand-embroidered quilts representing centuries of rural storytelling.",
    descBn: "শতাব্দী প্রাচীন গ্রামীণ গল্প ও ঐতিহ্যের হাতে সেলাই করা নকশী কাঁথা।"
  },
  {
    id: "jute-creations",
    nameEn: "Jute Creations",
    nameBn: "পাটজাত শিল্প",
    image: "https://i.pinimg.com/736x/26/a3/0e/26a30e9997f0d56cdc311d8932fdd8dd.jpg",
    descEn: "Eco-friendly, biodegradable bags and home utility products crafted from local golden fiber.",
    descBn: "এলাকার সোনালী আঁশ থেকে তৈরি পরিবেশ-বান্ধব ও পচনশীল ব্যাগ ও গৃহস্থালি পণ্য।"
  },
  {
    id: "clay-crafts",
    nameEn: "Clay Crafts",
    nameBn: "মৃৎশিল্প",
    image: "https://i.pinimg.com/736x/40/0f/37/400f37d2a80e7821e8f7edd4bfff6227.jpg",
    descEn: "Terracotta and pottery items molded by generational artisans utilizing natural river clay.",
    descBn: "প্রাকৃতিক নদীর কাদামাটি ব্যবহার করে বংশানুক্রমিক কারিগরদের তৈরি টেরাকোটা ও মৃৎশিল্প।"
  },
  {
    id: "bamboo-crafts",
    nameEn: "Bamboo Crafts",
    nameBn: "বাঁশ ও বেত শিল্প",
    image: "https://i.pinimg.com/1200x/f9/7f/b8/f97fb84232eb42f58bfeff332eef560f.jpg",
    descEn: "Durable hand-woven baskets, furniture and home decor carved from seasoned bamboo.",
    descBn: "পরিপক্ক বাঁশ ও বেত থেকে তৈরি টেকসই ঝুড়ি, আসবাবপত্র এবং নান্দনিক গৃহসজ্জা।"
  },
  {
    id: "handloom-clothing",
    nameEn: "Handloom Clothing",
    nameBn: "তাঁত ও বুনন শিল্প",
    image: "https://i.pinimg.com/736x/05/7a/83/057a83b5ba8582e004ee6983e21ec241.jpg",
    descEn: "Authentic Jamdani sarees, cotton shawls, and woven fabrics made on traditional wooden looms.",
    descBn: "ঐতিহ্যবাহী কাঠের তাঁতে বোনা আসল জামদানি শাড়ি, সুতি শাল এবং বুনন পোশাক।"
  },
  {
    id: "homemade-food",
    nameEn: "Homemade Food",
    nameBn: "ঘরে তৈরি খাবার",
    image: "https://i.pinimg.com/1200x/a2/72/c1/a272c14d3d594bc995d21c8612e9889a.jpg",
    descEn: "Traditional pure spices, honey, pitha mixes and native pickles made with authentic family recipes.",
    descBn: "পারিবারিক রেসিপিতে তৈরি খাঁটি মশলা, সুন্দরবনের মধু, পিঠার চালের গুঁড়ো এবং আচার।"
  },
  {
    id: "jewellery",
    nameEn: "Jewellery",
    nameBn: "গহনা শিল্প",
    image: "https://i.pinimg.com/1200x/7b/a2/09/7ba209976751bbc79169ae8f8b29675f.jpg",
    descEn: "Traditional handcrafted necklaces, clay beads, and metal jewelry carrying local folk heritage.",
    descBn: "ঐতিহ্যবাহী হাতে তৈরি মালা, মাটির পুঁতি এবং ধাতব অলঙ্কার যা ধারণ করে দেশীয় লোকজ সংস্কৃতি।"
  }
];

export const ARTISANS = [
  {
    id: "artisan-rahima",
    nameEn: "Rahima Begum",
    nameBn: "রাহিমা বেগম",
    districtEn: "Jamalpur",
    districtBn: "জামালপুর",
    experienceYears: 24,
    avatar: "https://i.pinimg.com/736x/fb/52/fa/fb52fa410d9d37e31ea136faae8ec358.jpg",
    bioEn: "Rahima is a master of Nakshi Katha. She runs a cooperative in Jamalpur helping over 40 rural women earn their livelihood through embroidery.",
    bioBn: "রাহিমা নকশী কাঁথা বুননের একজন দক্ষ কারিগর। তিনি জামালপুরে একটি সমবায় সমিতি পরিচালনা করেন যা ৪০ জনেরও বেশি গ্রামীণ নারীর আয়ের সুযোগ তৈরি করেছে।",
    rating: 4.9,
    specialtyEn: "Classic running stitch and floral motifs",
    specialtyBn: "চিরায়ত ফোঁড় সেলাই এবং চমৎকার ফুলের নকশা"
  },
  {
    id: "artisan-jahanara",
    nameEn: "Jahanara Bibi",
    nameBn: "জাহানারা বিবি",
    districtEn: "Mymensingh",
    districtBn: "ময়মনসিংহ",
    experienceYears: 18,
    avatar: "https://i.pinimg.com/736x/50/57/8e/50578e189627b533ac3a1a8db1550b8e.jpg",
    bioEn: "Jahanara specializes in golden fiber weaving. She breathes new life into raw jute, transforming it into contemporary fashion bags and accessories.",
    bioBn: "জাহানারা পাটজাত সোনালী আঁশের সুনিপুণ বুননে পারদর্শী। তিনি সাধারণ কাঁচা পাটকে আধুনিক ফ্যাশনেবল ব্যাগ ও ঘরোয়া সামগ্রীতে রূপান্তর করেন।",
    rating: 4.8,
    specialtyEn: "Organic dye patterns and braided jute rugs",
    specialtyBn: "প্রাকৃতিক রঙের নকশা এবং বেণি করা পাটের কার্পেট"
  },
  {
    id: "artisan-subal",
    nameEn: "Subal Paul",
    nameBn: "সুবল পাল",
    districtEn: "Sonargaon",
    districtBn: "সোনারগাঁও",
    experienceYears: 35,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
    bioEn: "Subal is a fifth-generation terracotta potter. He shapes clay on his traditional wooden wheel, keeping ancient pottery heritage alive.",
    bioBn: "সুবল পাল মাটির পাত্র তৈরিতে পঞ্চম প্রজন্মের কারিগর। তিনি তাঁর ঐতিহ্যবাহী কাঠের চাকার ঘূর্ণনে কাদামাটিকে নান্দনিক শিল্পকর্মে রূপ দেন।",
    rating: 4.95,
    specialtyEn: "Traditional Terracotta and Earthen Cookware",
    specialtyBn: "ঐতিহ্যবাহী পোড়ামাটি ও মাটির রান্নার তৈজসপত্র"
  },
  {
    id: "artisan-majid",
    nameEn: "Abdul Majid",
    nameBn: "আব্দুল মজিদ",
    districtEn: "Sylhet",
    districtBn: "সিলেট",
    experienceYears: 15,
    avatar: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&q=80&w=400",
    bioEn: "Abdul crafts baskets and lighting fixtures using premium Sylheti bamboo. His precision brings an elegant natural geometric warmth to modern interiors.",
    bioBn: "আব্দুল মজিদ সিলেটের প্রিমিয়াম বাঁশ ও বেত দিয়ে ঝুড়ি ও ঝাড়বাতি তৈরি করেন। তাঁর সূক্ষ্ম কাজ আধুনিক অন্দরমহলে এক প্রাকৃতিক উষ্ণতা যোগায়।",
    rating: 4.7,
    specialtyEn: "Fine lattice split-bamboo weaving",
    specialtyBn: "বাঁশ চিরে তৈরি করা সূক্ষ্ম জালিদার বুনন"
  },
  {
    id: "artisan-kusum",
    nameEn: "Kusum Rani",
    nameBn: "কুসুম রানী",
    districtEn: "Tangail",
    districtBn: "টাঙ্গাইল",
    experienceYears: 22,
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400",
    bioEn: "Kusum is an expert weaver in Tangail. Her intricate floral Jamdani weaving and fine cotton sarees showcase the peak of Bangladeshi textile heritage.",
    bioBn: "কুসুম রানী টাঙ্গাইলের একজন সুদক্ষ তাঁতি। সুতি শাড়ি ও জামদানিতে তাঁর নিখুঁত ফুলের কারুকাজ বাংলাদেশি বস্ত্র শিল্পের ঐতিহ্য বহন করে।",
    rating: 4.92,
    specialtyEn: "Traditional Tangail Jamdani weave",
    specialtyBn: "ঐতিহ্যবাহী টাঙ্গাইলের জামদানি বুনন"
  },
  {
    id: "artisan-fatema",
    nameEn: "Fatema Khatun",
    nameBn: "ফাতেমা খাতুন",
    districtEn: "Satkhira",
    districtBn: "সাতক্ষীরা",
    experienceYears: 12,
    avatar: "https://i.pinimg.com/1200x/13/15/da/1315da41a97f49b245b1bc681c76e596.jpg",
    bioEn: "Fatema collects wild honey from Sundarbans and makes organic Bengali pickles using family secret recipes dried on village rooftops under solar rays.",
    bioBn: "ফাতেমা সুন্দরবনের খাঁটি মধু সংগ্রহ করেন এবং ছাদে রোদে শুকানো পারিবারিক গোপন রেসিপিতে ঐতিহ্যবাহী সুস্বাদু আচার প্রস্তুত করেন।",
    rating: 4.85,
    specialtyEn: "Sundarbans honey and rooftop-cured pickles",
    specialtyBn: "সুন্দরবনের খাঁটি খলিশা মধু এবং রোদে শুকানো আচার"
  },
  {
    id: "artisan-shila",
    nameEn: "Shila Rani",
    nameBn: "শীলা রানী",
    districtEn: "Cox's Bazar",
    districtBn: "কক্সবাজার",
    experienceYears: 14,
    avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=400",
    bioEn: "Shila Rani is an award-winning artisan who crafts tribal and traditional jewelry using natural stones, terracotta clay, and brass.",
    bioBn: "শীলা রানী একজন জাতীয় পুরস্কারপ্রাপ্ত গহনা কারিগর। তিনি প্রাকৃতিক পাথর, পোড়ামাটি এবং তামা দিয়ে দৃষ্টিনন্দন ঐতিহ্যবাহী গহনা তৈরি করেন।",
    rating: 4.9,
    specialtyEn: "Terracotta and brass fusion tribal necklaces",
    specialtyBn: "পোড়ামাটি ও তামার ফিউশন করা চমৎকার আদিবাসী গহনা"
  }
];

export const PRODUCTS = [
  {
    id: "prod-nakshi-classic",
    nameEn: "Traditional Jamalpur Nakshi Katha",
    nameBn: "ঐতিহ্যবাহী জামালপুরের নকশী কাঁথা",
    price: 4500,
    rating: 4.9,
    reviewsCount: 42,
    category: "nakshi-katha",
    image: "https://i.pinimg.com/736x/cb/1e/11/cb1e117f76b2d98514bc81a54c9ab60d.jpg",
    gallery: [
      "https://i.pinimg.com/736x/cb/1e/11/cb1e117f76b2d98514bc81a54c9ab60d.jpg",
      "https://i.pinimg.com/736x/92/36/ee/9236ee55ff99f198f9bbda788ffb9c2a.jpg"
    ],
    artisanId: "artisan-rahima",
    materialsEn: ["100% Organic Cotton Thread", "Repurposed Village Handloom Cloth"],
    materialsBn: ["১০০% খাঁটি সুতির সুতা", "গ্রামীণ তাঁতের সুতি নরম কাপড়"],
    deliveryDays: 7,
    descEn: "This Nakshi Katha is carefully hand-embroidered over 3 months. It depicts village life with floral motifs and geometric borders.",
    descBn: "এই নকশী কাঁথাটি ৩ মাস ধরে যত্ন সহকারে হাতে সেলাই করা হয়েছে। এতে ফুলের মোটিফ এবং জ্যামিতিক বর্ডার সহ গ্রামীণ জীবনের ছবি ফুটিয়ে তোলা হয়েছে।",
    inStock: true,
    featured: true,
    trending: true
  },
  {
    id: "prod-nakshi-cushion",
    nameEn: "Hand-Embroidered Katha Cushion Cover",
    nameBn: "হাতে বোনা কুশন কভার (নকশী কাঁথা)",
    price: 650,
    rating: 4.75,
    reviewsCount: 15,
    category: "nakshi-katha",
    image: "https://i.pinimg.com/736x/92/36/ee/9236ee55ff99f198f9bbda788ffb9c2a.jpg",
    gallery: [
      "https://i.pinimg.com/736x/92/36/ee/9236ee55ff99f198f9bbda788ffb9c2a.jpg"
    ],
    artisanId: "artisan-rahima",
    materialsEn: ["Soft Khadi Cotton", "Multicolor Anchor Cotton Threads"],
    materialsBn: ["নরম খাদি সুতি কাপড়", "বহুরঙা সুতি এংকর সুতা"],
    deliveryDays: 4,
    descEn: "Add a splash of rural elegance to your workspace or living room with this colorful hand-embroidered Cushion Cover. Features classic rural bird and leaf motifs.",
    descBn: "আপনার বসার ঘর বা কর্মক্ষেত্রে গ্রামীণ সৌন্দর্যের ছোঁয়া আনতে এই চমৎকার নকশী কুশন কভারটি দারুণ। এতে ঐতিহ্যবাহী পাখি ও পাতার নিখুঁত ফোঁড় সেলাই ব্যবহার করা হয়েছে।",
    inStock: true,
    featured: false,
    trending: true
  },
  {
    id: "prod-jute-handbag",
    nameEn: "Handcrafted Golden Jute Handbag",
    nameBn: "হাতে তৈরি সোনালী পাটের হ্যান্ডব্যাগ",
    price: 1250,
    rating: 4.8,
    reviewsCount: 28,
    category: "jute-creations",
    image: "https://i.pinimg.com/736x/26/a3/0e/26a30e9997f0d56cdc311d8932fdd8dd.jpg",
    gallery: [
      "https://i.pinimg.com/736x/26/a3/0e/26a30e9997f0d56cdc311d8932fdd8dd.jpg"
    ],
    artisanId: "artisan-jahanara",
    materialsEn: ["Premium Golden Jute Fiber", "Organic Cotton Lining", "Wooden Handles"],
    materialsBn: ["উন্নত সোনালী পাটের আঁশ", "অর্গানিক সুতি কাপড়ের লাইনিং", "কাঠের হাতল"],
    deliveryDays: 5,
    descEn: "An elegant, highly durable everyday handbag made of tightly-woven raw jute with smooth wood handles. Combining Bangladeshi heritage with eco-friendly design.",
    descBn: "একটি মার্জিত ও দীর্ঘস্থায়ী নিত্যদিনের হ্যান্ডব্যাগ যা ঘন বুননের কাঁচা পাট এবং মসৃণ কাঠের হাতল দিয়ে তৈরি। এটি বাংলাদেশী ঐতিহ্যের সাথে পরিবেশ-বান্ধব ডিজাইনের সমন্বয় ঘটায়।",
    inStock: true,
    featured: true,
    trending: true
  },
  {
    id: "prod-jute-basket",
    nameEn: "Braided Jute Nesting Baskets",
    nameBn: "পাটের তৈরি চমৎকার ঝুড়ি সেট",
    price: 950,
    rating: 4.7,
    reviewsCount: 19,
    category: "jute-creations",
    image: "https://i.pinimg.com/1200x/88/73/9d/88739dfcd0e75925433d1089e2512670.jpg",
    gallery: [
      "https://i.pinimg.com/1200x/88/73/9d/88739dfcd0e75925433d1089e2512670.jpg"
    ],
    artisanId: "artisan-jahanara",
    materialsEn: ["100% Natural Braided Jute", "Organic Cotton Stitching Thread"],
    materialsBn: ["১০০% প্রাকৃতিক বেণি করা পাট", "জৈব সুতি সেলাই সুতা"],
    deliveryDays: 4,
    descEn: "A set of eco-friendly nesting baskets crafted from braided raw jute. Perfect for organizing toys, books, or adding a rustic charm to your shelves.",
    descBn: "পাটের তৈরি পরিবেশ-বান্ধব ঝুড়ির একটি সেট। এটি খেলনা ও বই গোছানোর জন্য বা তাকগুলোতে একটি চমৎকার গ্রামীণ সৌন্দর্য যোগ করার জন্য উপযুক্ত।",
    inStock: true,
    featured: false,
    trending: true
  },
  {
    id: "prod-jute-mat",
    nameEn: "Handwoven Jute Floor Mat",
    nameBn: "হাতে বোনা পাটের ফ্লোর ম্যাট",
    price: 1550,
    rating: 4.85,
    reviewsCount: 22,
    category: "jute-creations",
    image: "https://i.pinimg.com/736x/85/b2/31/85b23164c7017a892c483cb0fa0f69e3.jpg",
    gallery: [
      "https://i.pinimg.com/736x/85/b2/31/85b23164c7017a892c483cb0fa0f69e3.jpg"
    ],
    artisanId: "artisan-jahanara",
    materialsEn: ["Sturdy Natural Jute Yarn", "Traditional Handloom Weave"],
    materialsBn: ["মজবুত প্রাকৃতিক পাটের সুতা", "ঐতিহ্যবাহী তাঁতের বুনন"],
    deliveryDays: 6,
    descEn: "This thick, beautifully woven jute floor mat is ideal for high-traffic areas, bringing an organic texture and natural warmth to any room.",
    descBn: "এই ঘন ও সুন্দরভাবে বোনা পাটের ম্যাটটি যেকোনো ঘরে একটি জৈব টেক্সচার এবং প্রাকৃতিক উষ্ণতা নিয়ে আসে।",
    inStock: true,
    featured: true,
    trending: false
  },
  {
    id: "prod-clay-pottery",
    nameEn: "Sonargaon Terracotta Earthen Vase",
    nameBn: "সোনারগাঁও মাটির টেরাকোটা ফুলদানি",
    price: 850,
    rating: 4.9,
    reviewsCount: 19,
    category: "clay-crafts",
    image: "https://i.pinimg.com/736x/40/0f/37/400f37d2a80e7821e8f7edd4bfff6227.jpg",
    gallery: [
      "https://i.pinimg.com/736x/40/0f/37/400f37d2a80e7821e8f7edd4bfff6227.jpg",
      "https://i.pinimg.com/1200x/54/81/45/5481459180e88f7a8e58366f8aa7f518.jpg",
      "https://i.pinimg.com/736x/55/f6/2f/55f62fb40d189c752525382825050009.jpg"
    ],
    artisanId: "artisan-subal",
    materialsEn: ["Natural Silt Clay", "River Silt Wash", "Traditional Wood Fire kiln"],
    materialsBn: ["প্রাকৃতিক পলি মাটি", "নদীর কাদার প্রলেপ", "ঐতিহ্যবাহী কাঠের চুলা"],
    deliveryDays: 5,
    descEn: "Molded by hand on a wooden potter's wheel, this terracotta vase showcases traditional folk relief carvings. The reddish-clay glow provides a rustic warmth to any contemporary living room.",
    descBn: "ঐতিহ্যবাহী কাঠের চাকায় নিজ হাতে তৈরি এই মৃৎ ফুলদানিটিতে চমৎকার লোকজ নকশা খোদাই করা হয়েছে। এর লালচে মাটির প্রাকৃতিক উজ্জ্বলতা ঘরের কোণে এক গ্রামীণ আভিজাত্য এনে দেবে।",
    inStock: true,
    featured: false,
    trending: true
  },
  {
    id: "prod-clay-tea-set",
    nameEn: "Handcrafted Earthen Clay Tea Set",
    nameBn: "কারুকার্যখচিত মাটির চা সেট",
    price: 1500,
    rating: 4.95,
    reviewsCount: 22,
    category: "clay-crafts",
    image: "https://i.pinimg.com/1200x/54/81/45/5481459180e88f7a8e58366f8aa7f518.jpg",
    gallery: [
      "https://i.pinimg.com/1200x/54/81/45/5481459180e88f7a8e58366f8aa7f518.jpg"
    ],
    artisanId: "artisan-subal",
    materialsEn: ["Finest River Clay", "Natural Glaze Finish"],
    materialsBn: ["উন্নত নদীর লাল মাটি", "প্রাকৃতিক উজ্জ্বল পলিশ"],
    deliveryDays: 6,
    descEn: "Hand-painted traditional clay teacups with a rustic teapot molded from rich river silt clay. Keeps your local tea piping hot with a subtle, earthy aroma.",
    descBn: "নদীর উর্বর মাটি দিয়ে পরম যত্নে তৈরি চমৎকার মাটির কেতলি এবং চা পানের কাপের সেট। এটি চা-কে দীর্ঘক্ষণ গরম রাখে এবং পরিবেশনে ঐতিহ্যবাহী মাটির ছোঁয়া যোগ করে।",
    inStock: true,
    featured: true,
    trending: false
  },
  {
    id: "prod-clay-plate",
    nameEn: "Decorative Clay Alpana Wall Plate",
    nameBn: "মাটির আলপনা আঁকা দেয়াল সজ্জা",
    price: 650,
    rating: 4.8,
    reviewsCount: 8,
    category: "clay-crafts",
    image: "https://i.pinimg.com/736x/55/f6/2f/55f62fb40d189c752525382825050009.jpg",
    gallery: [
      "https://i.pinimg.com/736x/55/f6/2f/55f62fb40d189c752525382825050009.jpg"
    ],
    artisanId: "artisan-subal",
    materialsEn: ["Terracotta Clay", "Folk Alpana Acrylic Dyes"],
    materialsBn: ["পোড়ামাটি", "লোকজ আলপনা অ্যাক্রিলিক কালার"],
    deliveryDays: 4,
    descEn: "Intricately hand-etched clay wall plate painted with traditional white and red alpana folk motifs. High-contrast colors represent cultural festivals of rural Bengal.",
    descBn: "লাল এবং সাদা রঙে ঐতিহ্যবাহী গ্রামীণ আলপনা আঁকা চমৎকার মৃৎ দেয়াল প্লেট। লোকজ উৎসব ও সংস্কৃতির বহিঃপ্রকাশ হিসেবে এটি আপনার ঘরের সৌন্দর্য বহুগুণ বাড়িয়ে দেবে।",
    inStock: true,
    featured: false,
    trending: false
  },
  {
    id: "prod-bamboo-basket",
    nameEn: "Woven Sylhet Bamboo Utility Basket",
    nameBn: "সিলেটের নিখুঁত বাঁশের ঝুড়ি",
    price: 950,
    rating: 4.8,
    reviewsCount: 33,
    category: "bamboo-crafts",
    image: "https://i.pinimg.com/1200x/f9/7f/b8/f97fb84232eb42f58bfeff332eef560f.jpg",
    gallery: [
      "https://i.pinimg.com/1200x/f9/7f/b8/f97fb84232eb42f58bfeff332eef560f.jpg"
    ],
    artisanId: "artisan-majid",
    materialsEn: ["Seasoned Hill Bamboo", "Natural Cane binding"],
    materialsBn: ["পরিপক্ক পাহাড়ী বাঁশ", "প্রাকৃতিক বেতের বাঁধন"],
    deliveryDays: 3,
    descEn: "Hand-plaited using strong bamboo slivers, this multi-purpose basket combines incredible lightness with exceptional strength. Ideal for storing fruits, towels, or rustic home organization.",
    descBn: "মজবুত বাঁশের ফালি দিয়ে নিখুঁত বুননে তৈরি এই বহুমুখী ঝুড়িটি যেমন হালকা তেমন মজবুত। ফলমূল রাখা, তোয়ালে রাখা কিংবা ঘর সুন্দরভাবে গুছিয়ে রাখতে এটি অত্যন্ত কার্যকর।",
    inStock: true,
    featured: true,
    trending: true
  },
  {
    id: "prod-handloom-saree",
    nameEn: "Tangail Jamdani Cotton Saree",
    nameBn: "টাঙ্গাইল সুতি জামদানি শাড়ি",
    price: 6800,
    rating: 4.95,
    reviewsCount: 56,
    category: "handloom-clothing",
    image: "https://i.pinimg.com/736x/05/7a/83/057a83b5ba8582e004ee6983e21ec241.jpg",
    gallery: [
      "https://i.pinimg.com/736x/05/7a/83/057a83b5ba8582e004ee6983e21ec241.jpg"
    ],
    artisanId: "artisan-kusum",
    materialsEn: ["Fine Organic Tangail Cotton", "Silver-Wrapped Silk Thread"],
    materialsBn: ["টাঙ্গাইলের মিহি সুতি সুতা", "রূপালী কাজ করা রেশমি সুতা"],
    deliveryDays: 8,
    descEn: "Woven thread by thread on handlooms, this cotton Jamdani saree features gorgeous geometrical and floral weaves ('Panna Hajar' motif). Very light, breathable and representing Bangladesh's legendary textile heritage.",
    descBn: "তাঁতে সুতা কেটে বোনা এই চমৎকার সুতি জামদানি শাড়িটিতে 'পান্না হাজার' জ্যামিতিক নকশা ফুটিয়ে তোলা হয়েছে। এটি অত্যন্ত হালকা, আরামদায়ক এবং বাংলাদেশের বিশ্ববিখ্যাত তাঁত শিল্পের গৌরব বহন করে।",
    inStock: true,
    featured: true,
    trending: true
  },
  {
    id: "prod-sundarban-honey",
    nameEn: "Wild Sundarbans Khulisha Honey",
    nameBn: "সুন্দরবনের খাঁটি খলিশা ফুল মধু",
    price: 750,
    rating: 4.8,
    reviewsCount: 61,
    category: "homemade-food",
    image: "https://i.pinimg.com/736x/09/72/db/0972db0425551345014aca8b3caa74ca.jpg",
    gallery: [
      "https://i.pinimg.com/736x/09/72/db/0972db0425551345014aca8b3caa74ca.jpg"
    ],
    artisanId: "artisan-fatema",
    materialsEn: ["100% Wild Raw Honey", "Sundarbans Khulisha Nectar"],
    materialsBn: ["১০০% প্রাকৃতিক খাঁটি মধু", "সুন্দরবনের খলিশা ফুলের মধু"],
    deliveryDays: 3,
    descEn: "Harvested ethically from the deep mangrove forests of the Sundarbans. This raw, unfiltered Khulisha flower honey is rich in antioxidants, light-golden in color, with a sweet floral note.",
    descBn: "সুন্দরবনের গহীন ম্যানগ্রোভ বন থেকে সংগৃহীত। রাসায়নিকমুক্ত, অপরিশোধিত এবং শতভাগ খাঁটি খলিশা ফুলের মধু যা অ্যান্টি-অক্সিডেন্ট সমৃদ্ধ, সোনালী রঙের এবং মনমাতানো সুবাসযুক্ত।",
    inStock: true,
    featured: false,
    trending: false
  },
  {
    id: "prod-organic-spices",
    nameEn: "Organic Stone-Ground Spice Set",
    nameBn: "গ্রামীণ শিল-পাটায় বাটা মশলা সেট",
    price: 550,
    rating: 4.9,
    reviewsCount: 30,
    category: "homemade-food",
    image: "https://i.pinimg.com/1200x/a2/72/c1/a272c14d3d594bc995d21c8612e9889a.jpg",
    gallery: [
      "https://i.pinimg.com/1200x/a2/72/c1/a272c14d3d594bc995d21c8612e9889a.jpg"
    ],
    artisanId: "artisan-fatema",
    materialsEn: ["Sun-Dried Red Chili", "Premium Organic Turmeric"],
    materialsBn: ["রোদে শুকানো লাল মরিচ", "উন্নত জাতের খাঁটি হলুদ"],
    deliveryDays: 3,
    descEn: "Authentically hand-ground pure turmeric and red chili powder prepared by village mothers using traditional stone-grinders. Chemical-free, preserving native flavor.",
    descBn: "গ্রামীণ মায়েদের দ্বারা শিল-পাটায় বেটে প্রস্তুতকৃত শতভাগ খাঁটি হলুদ ও মরিচ গুড়ো। কোনো প্রকার কৃত্রিম রঙ বা প্রিজারভেটিভ ছাড়াই তৈরি এই মশলা রান্নায় অনন্য স্বাদ ও সুবাস আনে।",
    inStock: true,
    featured: true,
    trending: true
  },
  {
    id: "prod-homemade-pickles",
    nameEn: "Traditional Rooftop-Cured Mango Pickle",
    nameBn: "ঘরে তৈরি রোদে শুকানো আমের আচার",
    price: 420,
    rating: 4.85,
    reviewsCount: 25,
    category: "homemade-food",
    image: "https://i.pinimg.com/1200x/b3/03/27/b30327a4914a52663346b005dc7ec128.jpg",
    gallery: [
      "https://i.pinimg.com/1200x/b3/03/27/b30327a4914a52663346b005dc7ec128.jpg"
    ],
    artisanId: "artisan-fatema",
    materialsEn: ["Green Mangoes", "Cold-Pressed Mustard Oil", "Secret Family Spices"],
    materialsBn: ["কাঁচা আম", "খাঁটি ঘানির সরিষার তেল", "ঘরোয়া স্পেশাল মশলা"],
    deliveryDays: 3,
    descEn: "Tangy, solar-cured raw mango pieces steeped in premium cold-pressed mustard oil and village spices. Made following timeless maternal grandmother recipes.",
    descBn: "দিদিমা ও ঠাকুমাদের ঐতিহ্যবাহী রেসিপিতে তৈরি টক-ঝাল-মিষ্টি আমের আচার। খাঁটি সরিষার তেল ও বাছাইকৃত মশলায় তৈরি এই আচার রোদে শুকিয়ে বোতলজাত করা হয়।",
    inStock: true,
    featured: false,
    trending: true
  },
  {
    id: "prod-nakshi-pitha",
    nameEn: "Artisanal Handmade Nakshi Pitha Set",
    nameBn: "গ্রামীণ কারুকার্যখচিত নকশী পিঠা",
    price: 480,
    rating: 4.9,
    reviewsCount: 18,
    category: "homemade-food",
    image: "https://i.pinimg.com/736x/f5/c8/d1/f5c8d101c3d07dd98b3e9b6614834158.jpg",
    gallery: [
      "https://i.pinimg.com/736x/f5/c8/d1/f5c8d101c3d07dd98b3e9b6614834158.jpg"
    ],
    artisanId: "artisan-fatema",
    materialsEn: ["Premium Atap Rice Flour", "Sundarban Honey/Date Jaggery Syrup"],
    materialsBn: ["দেশী আতপ চালের গুঁড়ো", "সুন্দরবনের মধু/খেজুরের গুড়ের রস"],
    deliveryDays: 4,
    descEn: "Crispy and sweet traditional rice-flour deep-fried pastries designed with intricate hand-carved floral patterns. A legendary winter snack representing Bangladeshi hospitality.",
    descBn: "চালের গুঁড়ো ও খেজুরের রস দিয়ে অত্যন্ত নিখুঁত কারুকাজে তৈরি কুড়কুড়ে সুস্বাদু নকশী পিঠা। গ্রামীণ অতিথি আপ্যায়নের এক অবিচ্ছেদ্য লোকজ মিষ্টি খাবার ঐতিহ্য।",
    inStock: true,
    featured: false,
    trending: false
  },
  {
    id: "prod-terracotta-necklace",
    nameEn: "Terracotta Hand-Painted Choker Necklace",
    nameBn: "হাতে আঁকা পোড়ামাটির চোকার হার",
    price: 950,
    rating: 4.9,
    reviewsCount: 16,
    category: "jewellery",
    image: "https://i.pinimg.com/1200x/7b/a2/09/7ba209976751bbc79169ae8f8b29675f.jpg",
    gallery: [
      "https://i.pinimg.com/1200x/7b/a2/09/7ba209976751bbc79169ae8f8b29675f.jpg"
    ],
    artisanId: "artisan-shila",
    materialsEn: ["Fired Terracotta Clay Beads", "Folk Acrylic Paint", "Adjustable Jute Cord"],
    materialsBn: ["পোড়ামাটির তৈরি পুঁতি", "লোকজ অ্যাক্রিলিক রঙ", "অ্যাডজাস্টেবল পাটের সুতো"],
    deliveryDays: 4,
    descEn: "Hand-sculpted river clay beads, kiln-fired and intricately hand-painted with vibrant folk motifs. Light and comfortable, making a bold ethnic fashion statement.",
    descBn: "উন্নত মাটির ছাঁচে তৈরি পোড়ামাটির চমৎকার মালা ও গহনা সেট। এতে ঐতিহ্যবাহী বৈশাখী ও লোকজ মোটিফের রঙের আলপনা নিখুঁতভাবে হাতে আঁকা হয়েছে।",
    inStock: true,
    featured: true,
    trending: true
  },
  {
    id: "prod-brass-necklace",
    nameEn: "Artisanal Brass Filigree Pendant Necklace",
    nameBn: "ব্রাস ফিলিগ্রি পেণ্ডেন্ট নেকলেস",
    price: 1350,
    rating: 4.85,
    reviewsCount: 11,
    category: "jewellery",
    image: "https://i.pinimg.com/1200x/84/43/12/844312e4568e9c28c1af28397b505894.jpg",
    gallery: [
      "https://i.pinimg.com/1200x/84/43/12/844312e4568e9c28c1af28397b505894.jpg"
    ],
    artisanId: "artisan-shila",
    materialsEn: ["Pure Brass Filigree Plate", "Handcrafted Glass Beads", "Waxed Cotton Cord"],
    materialsBn: ["খাঁটি ব্রাস/তামার মেটাল পাত", "হাতে তৈরি কাঁচের পুঁতি", "মোম করা সুতির সুতো"],
    deliveryDays: 5,
    descEn: "Exquisite brass metal plate with classical hand-hammered filigree designs suspended on handcrafted organic strings with native colorful beads.",
    descBn: "অসাধারণ ব্রাস (পিতল ও তামা) কুঁদে তৈরি কারুকার্যময় পেণ্ডেন্ট সেট। আভিজাত্য এবং সংস্কৃতির এক অপূর্ব মেলবন্ধন যা যেকোনো আধুনিক পোশাকের সাথে দারুণ মানিয়ে যায়।",
    inStock: true,
    featured: false,
    trending: true
  }
];

export const REVIEWS = [
  {
    id: "rev-1",
    userName: "Sajid Ahmed",
    rating: 5,
    date: "June 15, 2026",
    commentEn: "Absolutely premium quality! The Nakshi Katha is even more detailed in person. I can feel the warmth and effort that went into it. Incredible platform!",
    commentBn: "অসাধারণ প্রিমিয়াম মান! নকশী কাঁথাটি সামনাসামনি দেখলে আরও চমৎকার লাগে। প্রতিটি সুতোয় কারিগরের ভালোবাসা অনুভব করা যায়। অনন্য উদ্যোগ!"
  },
  {
    id: "rev-2",
    userName: "Nusrat Jahan",
    rating: 5,
    date: "May 28, 2026",
    commentEn: "The handloom Jamdani saree is so soft, lightweight, and elegant. GrameenCraft connected me directly to Kusum Rani, and that felt so heartwarming.",
    commentBn: "তাঁতের জামদানি শাড়িটি অত্যন্ত নরম, হালকা এবং অভিজাত। গ্রামীণ ক্রাফটের কারণে আমি কারিগর কুসুম রানীর সাথে সরাসরি সংযোগ অনুভব করেছি।"
  },
  {
    id: "rev-3",
    userName: "Michael K.",
    rating: 4.8,
    date: "April 12, 2026",
    commentEn: "I ordered the terracotta vase and bamboo baskets for my home in Germany. Arrived in pristine condition. Knowing Abdul and Subal's generational stories made it precious.",
    commentBn: "আমি জার্মানির বাড়ির জন্য মাটির পাত্র এবং বাঁশের ঝুড়ি অর্ডার করেছিলাম। নিখুঁতভাবে পৌঁছেছে। আব্দুল এবং সুবলের পারিবারিক ইতিহাস জেনে পণ্যগুলো আরও মূল্যবান মনে হচ্ছে।"
  }
];

export const TRANSLATIONS = {
  en: {
    appName: "GrameenCraft",
    tagline: "Every Product Tells A Story",
    taglineSub: "Crafted By Villages, Shared With The World",
    searchPlaceholder: "Search handmade products, villages...",
    navHome: "Home",
    navShop: "Shop",
    navArtisans: "Artisans",
    navStories: "Customer Stories",
    navCart: "Cart",
    navProfile: "Profile",
    heroHeading: "Discover Authentic Handcrafted Bangladesh",
    heroSub: "Connecting rural master artisans directly with your home. Discover eco-friendly, timeless crafts that sustain villages and preserve cultural history.",
    btnShop: "Shop Collection",
    btnMeet: "Meet Artisans",
    statArtisans: "500+ Artisans",
    statProducts: "2,000+ Products",
    statVillages: "50+ Villages",
    catTitle: "Featured Heritage Categories",
    catSub: "Carefully selected categories celebrating native raw materials and ancestral craftsmanship.",
    trendingTitle: "Trending Handcrafted Creations",
    trendingSub: "The most appreciated authentic creations of the season, handmade with love.",
    artisanTitle: "Meet Our Master Artisans",
    artisanSub: "The heartbeat of GrameenCraft. These passionate creators preserve Bangladesh's soul.",
    storyTitle: "Hear Heritage Story",
    storyGenerating: "Listening to village whispers...",
    storyModalTitle: "The Craft's Living Heritage",
    storyDisclaimer: "Heritage narratives generated server-side by AI based on cultural traditions.",
    storyBy: "Handcrafted By",
    district: "District",
    experience: "Experience",
    years: "Years",
    specialty: "Specialty",
    materials: "Materials",
    delivery: "Delivery & Return",
    deliveryText: "Ships in biodegradable packing. Delivery in {days} working days.",
    inStock: "In Stock",
    outOfStock: "Sold Out",
    quickView: "Quick View",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    addedToCart: "Added to cart!",
    wishlistAdded: "Added to wishlist!",
    wishlistRemoved: "Removed from wishlist!",
    whyTitle: "Why Choose GrameenCraft?",
    why1Title: "100% Direct Artisan Profits",
    why1Desc: "We eliminate exploitative middlemen. Every Taka earned goes directly to support the artisan families.",
    why2Title: "Preserving Ancient Heritage",
    why2Desc: "Every purchase keeps traditional stitches, clay molds, and handlooms alive for the next generation.",
    why3Title: "Eco-Friendly & Sustainable",
    why3Desc: "Crafted purely from native jute, bamboo, river clay, and organic cotton. Gentle on the earth.",
    cartTitle: "Your Shopping Cart",
    cartEmpty: "Your basket is currently empty. Explore our villages to add crafts!",
    cartSummary: "Order Summary",
    subtotal: "Subtotal",
    shipping: "Organic Delivery",
    total: "Total",
    checkout: "Proceed to Checkout",
    checkoutTitle: "Secure Heritage Checkout",
    shippingAddress: "Shipping Information",
    fullName: "Full Name",
    address: "Village / Street Address",
    phone: "Phone Number",
    districtLabel: "District",
    paymentMethod: "Payment Method",
    cod: "Cash on Delivery",
    bKash: "bKash / Nagad (Mobile Wallet UI)",
    card: "Credit / Debit Card",
    confirmOrder: "Place Order (৳{total})",
    orderSuccess: "Order Placed Successfully!",
    orderSuccessSub: "Thank you for supporting rural livelihoods. We have sent a confirmation. Your story continues...",
    backToHome: "Return to Home",
    loginTitle: "Welcome to GrameenCraft",
    loginSub: "Sign in to connect with rural artisans and track your cultural orders.",
    email: "Email Address",
    password: "Password",
    rememberMe: "Remember me",
    forgotPass: "Forgot Password?",
    noAccount: "Don't have an account?",
    registerNow: "Register with village details",
    registerTitle: "Join GrameenCraft Family",
    registerSub: "Create an account to support sustainable rural craftsmanship.",
    alreadyHaveAccount: "Already have an account?",
    socialLogin: "Or connect via",
    profileTitle: "Your Grameen Dashboard",
    ordersTitle: "Your Order History",
    wishlistTitle: "Your Curated Wishlist",
    saveProfile: "Update Profile Info",
    savedMsg: "Profile information updated safely!",
    noOrders: "No heritage orders found yet. Start your journey!",
    bengaliLanguage: "বাংলা",
    englishLanguage: "English",
    madeWith: "Made with authentic warmth in Bangladesh © 2026 GrameenCraft.",
    viewDetails: "View Details",
    similarProducts: "Similar Village Crafts"
  },
  bn: {
    appName: "গ্রামীণক্রাফট",
    tagline: "প্রতিটি পণ্যের পেছনে আছে এক একটি গল্প",
    taglineSub: "গ্রামের মমতা, বিশ্ব দরবারে",
    searchPlaceholder: "হাতে তৈরি পণ্য বা গ্রামের নাম খুঁজুন...",
    navHome: "হোম",
    navShop: "দোকান",
    navArtisans: "কারিগরবৃন্দ",
    navStories: "গ্রাহকদের গল্প",
    navCart: "কার্ট",
    navProfile: "প্রোফাইল",
    heroHeading: "খুঁজে নিন খাঁটি ও ঐতিহ্যবাহী বাংলাদেশ",
    heroSub: "গ্রামীণ সুদক্ষ কারিগরদের সরাসরি যুক্ত করুন আপনার ঘরের সাথে। খুঁজে নিন পরিবেশবান্ধব ও কালজয়ী সামগ্রী যা গ্রামকে সচল রাখে এবং আমাদের সংস্কৃতিকে বাঁচিয়ে রাখে।",
    btnShop: "কালেকশন দেখুন",
    btnMeet: "কারিগরদের সাথে পরিচিত হন",
    statArtisans: "৫০০+ কারিগর",
    statProducts: "২,০০০+ পণ্য",
    statVillages: "৫০+ গ্রাম",
    catTitle: "ঐতিহ্যের বিশেষ ক্যাটাগরি",
    catSub: "দেশীয় কাঁচামাল এবং পূর্বপুরুষদের সুনিপুণ কারুকাজকে উদযাপিত করে এমন বিশেষ ক্যাটাগরি সমূহ।",
    trendingTitle: "জনপ্রিয় হস্তশিল্প কালেকশন",
    trendingSub: "এ সপ্তাহের সবচেয়ে প্রশংসিত ও ভালোবাসা দিয়ে তৈরি খাঁটি হস্তশিল্প সমূহ।",
    artisanTitle: "আমাদের মাস্টার কারিগরবৃন্দ",
    artisanSub: "গ্রামীণক্রাফটের প্রাণ। এই একনিষ্ঠ স্রষ্টারা আমাদের ঐতিহ্য ও সংস্কৃতিকে বুকে ধারণ করে আছেন।",
    storyTitle: "হেরিটেজ গল্প শুনুন",
    storyGenerating: "গ্রামের ফিসফিসানি শোনা যাচ্ছে...",
    storyModalTitle: "ঐতিহ্যের জীবন্ত আখ্যান",
    storyDisclaimer: "সাংস্কৃতিক ঐতিহ্যের ওপর ভিত্তি করে এআই (AI) দ্বারা গল্পটি তৈরি করা হয়েছে।",
    storyBy: "তৈরি করেছেন",
    district: "জেলা",
    experience: "অভিজ্ঞতা",
    years: "বছর",
    specialty: "বিশেষত্ব",
    materials: "ব্যবহৃত উপাদান",
    delivery: "ডেলিভারি ও রিটার্ন",
    deliveryText: "পরিবেশবান্ধব প্যাকেজিংয়ে পাঠানো হয়। {days} কার্যদিবসের মধ্যে ডেলিভারি সম্পন্ন হবে।",
    inStock: "স্টকে আছে",
    outOfStock: "স্টকে নেই",
    quickView: "এক পলকে",
    addToCart: "কার্ট-এ যোগ করুন",
    buyNow: "সরাসরি কিনুন",
    addedToCart: "কার্টে যোগ হয়েছে!",
    wishlistAdded: "উইশলিস্টে যুক্ত হয়েছে!",
    wishlistRemoved: "উইশলিস্ট থেকে সরানো হয়েছে!",
    whyTitle: "কেন গ্রামীণক্রাফট বেছে নেবেন?",
    why1Title: "১০০% সরাসরি কারিগরের লাভ",
    why1Desc: "আমরা মধ্যস্বত্বভোগীদের অবসান ঘটিয়েছি। প্রতিটি টাকার লাভ সরাসরি কারিগর পরিবারগুলোর কাছে পৌঁছে যায়।",
    why2Title: "প্রাচীন সংস্কৃতির সুরক্ষা",
    why2Desc: "আপনার প্রতিটি ক্রয় ঐতিহ্যবাহী সেলাই, মাটির ছাঁচ এবং তাঁত বোনার সংস্কৃতিকে নতুন প্রজন্মের জন্য টিকিয়ে রাখে।",
    why3Title: "সম্পূর্ণ পরিবেশবান্ধব",
    why3Desc: "খাঁটি পাট, বাঁশ, নদীর পলি মাটি ও সুতি কাপড়ে তৈরি। এটি প্রকৃতির জন্য একদম নিরাপদ।",
    cartTitle: "আপনার শপিং কার্ট",
    cartEmpty: "আপনার ঝুড়ি বর্তমানে শূন্য। পণ্য যোগ করতে গ্রামীণ কুঠিরগুলো ঘুরে দেখুন!",
    cartSummary: "অর্ডার বিবরণী",
    subtotal: "উপমোট",
    shipping: "পরিবেশবান্ধব ডেলিভারি",
    total: "সর্বমোট",
    checkout: "চেকআউট-এ যান",
    checkoutTitle: "নিরাপদ হেরিটেজ চেকআউট",
    shippingAddress: "ডেলিভারি ঠিকানা",
    fullName: "পূর্ণ নাম",
    address: "গ্রাম / রাস্তার ঠিকানা",
    phone: "মোবাইল নম্বর",
    districtLabel: "জেলা",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    cod: "ক্যাশ অন ডেলিভারি (হাতে পেয়ে টাকা)",
    bKash: "বিকাশ / নগদ (মোবাইল ওয়ালেট)",
    card: "ক্রেডিট / ডেবিট কার্ড",
    confirmOrder: "অর্ডার সম্পন্ন করুন (৳{total})",
    orderSuccess: "অর্ডার সফলভাবে সম্পন্ন হয়েছে!",
    orderSuccessSub: "গ্রামীণ জীবিকাকে সমর্থন করার জন্য ধন্যবাদ। আমরা অর্ডার নিশ্চিতকরণ ইমেল পাঠিয়েছি। আপনার গল্প চলবে...",
    backToHome: "হোমে ফিরে যান",
    loginTitle: "গ্রামীণক্রাফটে স্বাগতম",
    loginSub: "গ্রামীণ কারিগরদের সাথে যুক্ত হতে এবং অর্ডারের খোঁজ রাখতে লগইন করুন।",
    email: "ইমেইল ঠিকানা",
    password: "পাসওয়ার্ড",
    rememberMe: "লগইন তথ্য মনে রাখুন",
    forgotPass: "পাসওয়ার্ড ভুলে গেছেন?",
    noAccount: "নতুন গ্রাহক?",
    registerNow: "গ্রামের ঠিকানায় রেজিস্টার করুন",
    registerTitle: "গ্রামীণক্রাফট পরিবারে যোগ দিন",
    registerSub: "টেকসই গ্রামীণ শিল্পকে সমর্থন করতে একটি অ্যাকাউন্ট খুলুন।",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    socialLogin: "অন্যান্য মাধ্যমে যুক্ত হন",
    profileTitle: "আপনার গ্রামীণ ড্যাশবোর্ড",
    ordersTitle: "আপনার অর্ডার সমূহ",
    wishlistTitle: "আপনার উইশলিস্ট",
    saveProfile: "প্রোফাইল আপডেট করুন",
    savedMsg: "প্রোফাইল তথ্য সুরক্ষিতভাবে আপডেট হয়েছে!",
    noOrders: "কোন অর্ডার পাওয়া যায়নি। ঐতিহ্যবাহী ক্রাফট দিয়ে শুরু করুন!",
    bengaliLanguage: "বাংলা",
    englishLanguage: "English",
    madeWith: "মমতার সাথে বাংলাদেশে তৈরি © ২০২৬ গ্রামীণক্রাফট।",
    viewDetails: "বিস্তারিত দেখুন",
    similarProducts: "অনুরূপ গ্রামীণ হস্তশিল্প"
  }
};
